spring:
  application:
    name: inventario-service

  r2dbc:
    url: ${INVENTARIO_DB_URL}
    username: ${INVENTARIO_DB_USER}
    password: ${INVENTARIO_DB_PASS}

  main:
    allow-bean-definition-overriding: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework: WARN

productos:
  service:
    url: ${PRODUCTOS_SERVICE_URL}
